# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20190511_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
