# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190518_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
