# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-19 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20190518_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='upated',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
