# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-08 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewed',
            options={'ordering': ['-timestamp'], 'verbose_name': 'object_viewed', 'verbose_name_plural': 'objects_viewed'},
        ),
    ]
